FROM seunmul/ros:noetic-full-arm64

ENV DEBIAN_FRONTEND=noninteractive

# Install basic dependencies
# RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F42ED6FBAB17C654 && apt-get update && apt-get install -y \
    python3-pip \
    python3-catkin-tools \
    git \
    && rm -rf /var/lib/apt/lists/*

# Install Gazebo (if not included in base image)
RUN apt-get update && apt-get install -y \
    gazebo11 \
    ros-noetic-gazebo-ros-pkgs \
    ros-noetic-gazebo-ros-control \
    ros-noetic-pcl-ros \
    ros-noetic-ddynamic-reconfigure \
    ros-noetic-robot-localization \
    ros-noetic-move-base \
    && rm -rf /var/lib/apt/lists/*

# ERROR: scipy 1.10.1 has requirement numpy<1.27.0,>=1.19.5, but you'll have numpy 1.17.4 which is incompatible.
# Install Python packages from your pip_packages.txt
RUN pip3 install --no-cache-dir \
    casadi \
    rockit-meco \
    numpy==1.20.0 \
    matplotlib \
    transforms3d 

# RUN pip install osqp
RUN git clone --recursive https://github.com/osqp/osqp && cd osqp && git checkout v0.6.3 && git submodule update --recursive && mkdir build && cd build && cmake -G "Unix Makefiles" .. && \
    cmake --build . --target install
RUN git clone https://github.com/robotology/osqp-eigen.git && cd osqp-eigen && mkdir build && cd build && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/ ../ && make && make install

RUN apt-get update && apt-get install -y \
    ros-noetic-serial \
    ros-noetic-velodyne-description \
    ros-noetic-velodyne-simulator \
    libnlopt-dev

# Set up workspace
RUN mkdir -p /ros1_ws/src
WORKDIR /ros1_ws

# Source ROS setup in bashrc
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN echo "source /ros1_ws/devel/setup.bash" >> ~/.bashrc

CMD ["bash"]
